name: movies_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  animated_bottom_navigation_bar: ^1.1.0
  convex_bottom_bar: ^3.1.0+1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  shimmer: ^2.0.0
  flutter_secure_storage: ^6.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
  
    - assets/logos/
    - assets/backgrounds/

